language: php
php:
    - 5.6
services:
    - redis-server
install:
    - composer install
before_script:
    - curl http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -o php-cs-fixer.phar
script:
    - php -n php-cs-fixer.phar fix --dry-run --diff-format udiff src
    - "./vendor/bin/phpunit"
